In [1]:
import pandas as pd

In [2]:
df= pd.read_csv('../datasets/processed/df_15min.csv')
df.head()

   SCATS Number  NB_LATITUDE  NB_LONGITUDE  Traffic_flow             Datetime
0           970    -37.86703     145.09159            86  2006-10-01 00:00:00
1           970    -37.86703     145.09159            32  2006-10-02 00:00:00
2           970    -37.86703     145.09159            26  2006-10-03 00:00:00
3           970    -37.86703     145.09159            32  2006-10-04 00:00:00
4           970    -37.86703     145.09159            40  2006-10-05 00:00:00

In [3]:
print(df[["SCATS Number", "NB_LATITUDE", "NB_LONGITUDE"]].drop_duplicates().head(20))

     SCATS Number  NB_LATITUDE  NB_LONGITUDE
0             970   -37.867030    145.091590
31            970   -37.867350    145.091950
62            970   -37.867600    145.091460
93            970   -37.867230    145.091030
123          2000   -37.851683    145.094346
151          2000   -37.851930    145.094630
180          2000   -37.852210    145.094250
208          2000   -37.851870    145.094070
237          2200   -37.816310    145.098120
268          2200   -37.816550    145.098310
299          2200   -37.816820    145.098020
330          2200   -37.816480    145.097739
361          2820   -37.794770    145.030770
392          2820   -37.794800    145.030150
422          2825   -37.786610    145.062020
453          2827   -37.780930    145.077330
484          2827   -37.782087    145.077826
515          2827   -37.782670    145.077290
546          2827   -37.781270    145.076880
577          2846   -37.861267    145.058038

In [4]:
df_update = df[["SCATS Number", "NB_LATITUDE", "NB_LONGITUDE"]].drop_duplicates()
df_update

      SCATS Number  NB_LATITUDE  NB_LONGITUDE
0              970   -37.867030    145.091590
31             970   -37.867350    145.091950
62             970   -37.867600    145.091460
93             970   -37.867230    145.091030
123           2000   -37.851683    145.094346
...            ...          ...           ...
4042          4812   -37.829030    145.014560
4068          4821   -37.812850    145.008490
4099          4821   -37.812930    145.008650
4130          4821   -37.813120    145.008440
4161          4821   -37.812960    145.008300

[140 rows x 3 columns]

In [9]:
df_cleaned = df_update.groupby("SCATS Number")[["NB_LATITUDE", "NB_LONGITUDE"]].mean().reset_index()
df_cleaned

    SCATS Number  NB_LATITUDE  NB_LONGITUDE
0            970   -37.867303    145.091508
1           2000   -37.851923    145.094324
2           2200   -37.816540    145.098047
3           2820   -37.794785    145.030460
4           2825   -37.786610    145.062020
5           2827   -37.781739    145.077331
6           2846   -37.861304    145.057875
7           3001   -37.814655    145.022137
8           3002   -37.815162    145.026573
9           3120   -37.822895    145.057288
10          3122   -37.823857    145.064393
11          3126   -37.827847    145.098577
12          3127   -37.825227    145.077947
13          3180   -37.796213    145.083507
14          3662   -37.808953    145.027457
15          3682   -37.837475    145.096868
16          3685   -37.854897    145.093910
17          3804   -37.833642    145.062392
18          3812   -37.837490    145.060865
19          4030   -37.795330    145.061607
20          4032   -37.802298    145.061230
21          4034   -37.811850    145.059405
22          4035   -37.818156    145.058123
23          4040   -37.832872    145.055423
24          4043   -37.847160    145.052627
25          4051   -37.794143    145.069333
26          4057   -37.804975    145.081765
27          4063   -37.814372    145.080005
28          4262   -37.821550    145.015030
29          4263   -37.823056    145.024958
30          4264   -37.824128    145.034005
31          4266   -28.368973    108.782585
32          4270   -37.830227    145.032815
33          4272   -37.831883    145.046393
34          4273   -37.846590    145.044430
35          4321   -37.800838    145.049119
36          4324   -37.809332    145.036848
37          4335   -37.806215    145.035250
38          4812   -37.828913    145.015587
39          4821   -37.812965    145.008470

In [11]:
df_cleaned.to_csv("../datasets/processed/SCAT_cord.csv", index=False)